sudo: false
language: node_js
cache:
  directories:
  - $HOME/.npm
notifications:
  email: false
node_js:
- 8 # stable
- 6 # LTS
- 4 # maintenance
after_success:
- npm run coverage:upload
- npm run semantic-release
